sudo: required

language: cpp

script: make && make test

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
    - LIBSTDC_VERSION=5
    - CLANG_VERSION=3.6

matrix:
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc

before_install:
  # Prepare compilers
  - if [[ "$CXX" == "g++" || "$CC" == "gcc" ]]; then sh travis/install-gcc.sh; fi
  - if [[ "$CXX" == "clang++" || "$CC" == "clang" ]]; then sh travis/install-clang.sh; fi

  # Debug information
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then lsb_release -a; fi
  - uname -a
  - $CC --version
  - $CXX --version

cache:
  - apt
